In [2]:
!pip install pandas matplotlib seaborn --quiet

In [3]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

In [4]:
pd.set_option("display.max_rows", 10)

sns.set(style="whitegrid")



print("Setup complete")

Setup complete

In [5]:
from google. colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
from google.colab import files

import pandas as pd

uploaded = files.upload()

full_path = '/content/student.csv'

Saving student.csv to student.csv

In [9]:
df = pd.read_csv('/content/student.csv')

df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [10]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [11]:
print(df.columns)

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [12]:
for i, col in enumerate(df.columns):
  print(i,col)

0 id
1 name
2 class
3 mark
4 gender

In [14]:

for i, row in df.iterrows():    # iterate over rows
   print(i, row.to_dict())    #turns a row (a Series) into a {column: value} dictionary

0 {'id': 1, 'name': 'John Deo', 'class': 'Four', 'mark': 75, 'gender': 'female'}
1 {'id': 2, 'name': 'Max Ruin', 'class': 'Three', 'mark': 85, 'gender': 'male'}
2 {'id': 3, 'name': 'Arnold', 'class': 'Three', 'mark': 55, 'gender': 'male'}
3 {'id': 4, 'name': 'Krish Star', 'class': 'Four', 'mark': 60, 'gender': 'female'}
4 {'id': 5, 'name': 'John Mike', 'class': 'Four', 'mark': 60, 'gender': 'female'}
5 {'id': 6, 'name': 'Alex John', 'class': 'Four', 'mark': 55, 'gender': 'male'}
6 {'id': 7, 'name': 'My John Rob', 'class': 'Fifth', 'mark': 78, 'gender': 'male'}
7 {'id': 8, 'name': 'Asruid', 'class': 'Five', 'mark': 85, 'gender': 'male'}
8 {'id': 9, 'name': 'Tes Qry', 'class': 'Six', 'mark': 78, 'gender': nan}
9 {'id': 10, 'name': 'Big John', 'class': 'Four', 'mark': 55, 'gender': 'female'}
10 {'id': 11, 'name': 'Ronald', 'class': 'Six', 'mark': 89, 'gender': 'female'}
11 {'id': 12, 'name': 'Recky', 'class': 'Six', 'mark': 94, 'gender': 'female'}
12 {'id': 13, 'name': 'Kty', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
13 {'id': 14, 'name': 'Bigy', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
14 {'id': 15, 'name': 'Tade Row', 'class': nan, 'mark': 88, 'gender': 'male'}
15 {'id': 16, 'name': 'Gimmy', 'class': 'Four', 'mark': 88, 'gender': 'male'}
16 {'id': 17, 'name': 'Tumyu', 'class': 'Six', 'mark': 54, 'gender': 'male'}
17 {'id': 18, 'name': 'Honny', 'class': 'Five', 'mark': 75, 'gender': 'male'}
18 {'id': 19, 'name': 'Tinny', 'class': 'Nine', 'mark': 18, 'gender': 'male'}
19 {'id': 20, 'name': 'Jackly', 'class': 'Nine', 'mark': 65, 'gender': 'female'}
20 {'id': 21, 'name': 'Babby John', 'class': 'Four', 'mark': 69, 'gender': 'female'}
21 {'id': 22, 'name': 'Reggid', 'class': 'Seven', 'mark': 55, 'gender': 'female'}
22 {'id': 23, 'name': 'Herod', 'class': 'Eight', 'mark': 79, 'gender': 'male'}
23 {'id': 24, 'name': 'Tiddy Now', 'class': 'Seven', 'mark': 78, 'gender': 'male'}
24 {'id': 25, 'name': 'Giff Tow', 'class': 'Seven', 'mark': 88, 'gender': 'male'}
25 {'id': 26, 'name': 'Crelea', 'class': 'Seven', 'mark': 79, 'gender': 'male'}
26 {'id': 27, 'name': nan, 'class': 'Three', 'mark': 81, 'gender': nan}
27 {'id': 28, 'name': 'Rojj Base', 'class': 'Seven', 'mark': 86, 'gender': 'female'}
28 {'id': 29, 'name': 'Tess Played', 'class': 'Seven', 'mark': 55, 'gender': 'male'}
29 {'id': 30, 'name': 'Reppy Red', 'class': 'Six', 'mark': 79, 'gender': 'female'}
30 {'id': 31, 'name': 'Marry Toeey', 'class': 'Four', 'mark': 88, 'gender': 'male'}
31 {'id': 32, 'name': 'Binn Rott', 'class': 'Seven', 'mark': 90, 'gender': 'female'}
32 {'id': 33, 'name': 'Kenn Rein', 'class': 'Six', 'mark': 96, 'gender': 'female'}
33 {'id': 34, 'name': 'Gain Toe', 'class': 'Seven', 'mark': 69, 'gender': 'male'}
34 {'id': 35, 'name': 'Rows Noump', 'class': 'Six', 'mark': 88, 'gender': 'female'}

In [15]:
print(df[['id']])

    id
0    1
1    2
2    3
3    4
4    5
..  ..
30  31
31  32
32  33
33  34
34  35

[35 rows x 1 columns]

In [16]:
import pandas as pd

data = {
   'Name': ['Tom', 'Anna', 'Ravi', 'John'],
   'Age': [25, 30, 22, 28]
}

In [17]:
df=pd.DataFrame(data, index=['A','B','C','D'])

In [18]:
# loc examples
print("loc single label:")
print(df.loc['A'])

loc single label:
Name    Tom
Age      25
Name: A, dtype: object

In [19]:
print(df.loc[['A', 'B']])

   Name  Age
A   Tom   25
B  Anna   30

In [20]:
print("\nloc slicing (A to C, both included):")
print(df.loc['A':'C'])

loc slicing (A to C, both included):
   Name  Age
A   Tom   25
B  Anna   30
C  Ravi   22

In [21]:
df.loc[['A','B']]

   Name  Age
A   Tom   25
B  Anna   30

In [22]:
df.iloc [[1,2,3]]

   Name  Age
B  Anna   30
C  Ravi   22
D  John   28

In [23]:
df.head()

   Name  Age
A   Tom   25
B  Anna   30
C  Ravi   22
D  John   28

In [24]:
df = pd.read_csv('/content/drive/MyDrive/student.csv')

In [25]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [28]:
df.loc[:,['name','mark']]

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
..          ...   ...
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

[35 rows x 2 columns]

In [29]:
df.loc[:,['class','gender']]

    class  gender
0    Four  female
1   Three    male
2   Three    male
3    Four  female
4    Four  female
..    ...     ...
30   Four    male
31  Seven  female
32    Six  female
33  Seven    male
34    Six  female

[35 rows x 2 columns]

In [30]:
df.iloc[[0, 3, 5]]

   id        name class  mark  gender
0   1    John Deo  Four    75  female
3   4  Krish Star  Four    60  female
5   6   Alex John  Four    55    male

In [33]:
df.iloc[:,2]

0      Four
1     Three
2     Three
3      Four
4      Four
      ...
30     Four
31    Seven
32      Six
33    Seven
34      Six
Name: class, Length: 35, dtype: object

In [34]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [47]:
def __init_(self, name, mark):

  self.name = name

  self.mark = mark

In [50]:
def passed(self, threshold): # Method to check if student passed

  return self.mark >= threshold

In [51]:
threshold_mark = 75

students = []

In [58]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [60]:
df[df['mark']>80]

    id         name  class  mark  gender
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
..  ..          ...    ...   ...     ...
27  28    Rojj Base  Seven    86  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

[15 rows x 5 columns]

In [62]:
df[(df['mark']>80)&(df['gender']=='female')].head()

    id       name  class  mark  gender
10  11     Ronald    Six    89  female
11  12      Recky    Six    94  female
12  13        Kty  Seven    88  female
13  14       Bigy  Seven    88  female
27  28  Rojj Base  Seven    86  female

In [63]:
df[(df['mark']>80)|(df['class']=='four')].head()

    id      name  class  mark  gender
1    2  Max Ruin  Three    85    male
7    8    Asruid   Five    85    male
10  11    Ronald    Six    89  female
11  12     Recky    Six    94  female
12  13       Kty  Seven    88  female

In [88]:
import pandas as pd
df = pd.read_csv("/content/student.csv")

In [89]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [66]:
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [69]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
         ...
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, Length: 35, dtype: object

In [71]:
df[["name","mark"]]

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
..          ...   ...
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

[35 rows x 2 columns]

In [75]:
df.head(3)

   id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male
2   3    Arnold  Three    55    male

In [80]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [81]:
df[df["class"] == "Four"]

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

In [103]:
df.groupby("class")["score"].mean()

class
Eight    79.000000
Fifth    78.000000
Five     80.000000
Four     68.750000
Nine     41.500000
Seven    77.600000
Six      82.571429
Three    73.666667
Name: score, dtype: float64

In [104]:
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64

In [105]:
df.groupby("gender")["score"].mean()

gender
female    77.312500
male      71.588235
Name: score, dtype: float64

In [2]:
df.head()

NameError: name 'df' is not defined